name: mitmproxy_ri_client
description: A client for the mitmproxy Remote Interceptions addon.
version: 0.1.0
homepage: https://github.com/hacker1024/mitmproxy_ri_client.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
 web_socket_channel: ^2.2.0
 json_annotation: ^4.6.0
 freezed_annotation: ^2.0.3

dev_dependencies:
  lint: ^1.8.2
  build_runner: ^2.1.11
  json_serializable: ^6.3.1
  freezed: ^2.0.4
