name: mitmproxy_ri_client
description: A client for the mitmproxy Remote Interceptions addon.
version: 0.1.0
homepage: https://github.com/hacker1024/mitmproxy_ri_client.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
 web_socket_channel: ^2.4.0
 json_annotation: ^4.8.1
 freezed_annotation: ^2.2.0

dev_dependencies:
  lint: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  freezed: ^2.3.3
